SET SCHEMA FN71943;

CREATE VIEW V_TREATMENTS_DONE
AS
SELECT P.NAME, A.DATE, T.TYPE
FROM APPOINTMENTS A, PATIENTS P, ISDONE I, TREATMENTS T
WHERE A.PATIENTID = P.EGN
AND   A.APPOINTMENTID = I.APPOINTMENTID
AND   I.TREATMENTID = T.TREATMENTID;


CREATE VIEW V_DOCTOR_OFFERS
AS
SELECT D.NAME, T.TYPE, T.PRICE
FROM DOCTORS D, OFFERS O, TREATMENTS T
WHERE D.DOCID = O.DOCID
AND   O.TREATMENTID = T.TREATMENTID;