SET SCHEMA FN71943;

CREATE TABLE PATIENTS(
    EGN CHAR(10) NOT NULL PRIMARY KEY,
    PHONENUM CHAR(10),
    NAME VARCHAR(50),
    BIRTHDATE DATE,
    EMAIL VARCHAR(30)
);

CREATE TABLE DOCTORS(
    DOCID CHAR(6) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50),
    MAJOR VARCHAR(20),
    PHONENUM CHAR(10)
);

CREATE TABLE APPOINTMENTS(
    APPOINTMENTID VARCHAR(10) NOT NULL PRIMARY KEY,
    DATE DATE,
    TIME TIME,
    PATIENTID CHAR(10) NOT NULL REFERENCES PATIENTS(EGN),
    DOCID CHAR(6) NOT NULL REFERENCES DOCTORS(DOCID)
);

CREATE TABLE TREATMENTS(
    TREATMENTID VARCHAR(10) NOT NULL PRIMARY KEY,
    TYPE VARCHAR(60),
    PRICE INT
);

CREATE TABLE ISDONE(
    APPOINTMENTID VARCHAR(10) NOT NULL REFERENCES APPOINTMENTS(APPOINTMENTID),
    TREATMENTID VARCHAR(10) NOT NULL REFERENCES TREATMENTS(TREATMENTID)
);


CREATE TABLE OFFERS(
    DOCID CHAR(6) NOT NULL REFERENCES DOCTORS(DOCID),
    TREATMENTID VARCHAR(10) NOT NULL REFERENCES TREATMENTS(TREATMENTID)
);

